name       : liblangtag
version    : 0.6.2
release    : 1
source     :
    - https://bitbucket.org/tagoh/liblangtag/downloads/liblangtag-0.6.2.tar.bz2 : d6242790324f1432fb0a6fae71b6851f520b2c5a87675497cf8ea14c2924d52e
license    :
    - LGPL-3.0
    - MPL-2.0
component  : programming
summary    : An interface library to access tags for identifying languages
description: |
    An interface library to access tags for identifying languages.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
